{
 "title": "MLT Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "httpStatus",
    "label": "HTTP Status",
    "query": {
     "query": "{status!=\"\"}"
    }
   },
   {
    "name": "beast",
    "label": "HTTP Endpoint",
    "query": {
     "query": "{beast=~\".+\"}"
    }
   },
   {
    "name": "serviceVersion",
    "label": "Service Version",
    "query": {
     "query": "{service_version!=\"\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (beast)(rate(mythical_request_times_sum{beast=~\"${beast}\"}[1m]) / rate(mythical_request_times_count{beast=~\"${beast}\"}[1m])) * 55"
    }
   ]
  },
  {
   "title": "Overall Error %age",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(mythical_request_times_count{status!~\"[123]..\"}[1m]))/sum(increase(mythical_request_times_count[1m]))) * 100"
    }
   ]
  },
  {
   "title": "Error Percentages by Target",
   "type": "stat",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (beast)(increase(mythical_request_times_count{status!~\"[123]..\",beast=~\"${beast}\"}[5m])))/(sum by (beast)(increase(mythical_request_times_count{status!=\"\",beast=~\"${beast}\"}[5m]))) * 100",
     "legendFormat": "{{beast}}"
    }
   ]
  },
  {
   "title": "HTTP Status codes by Endpoint",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (status,beast,service_version)(increase(mythical_request_times_count{status=~\"${httpStatus}\",beast=~\"${beast}\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Highest Endpoint Latencies Over Last Minute",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, sum by (method,beast,service_version)(increase(mythical_request_times_sum{method=~\".+\", beast=~\"${beast}\"}[1m]) / increase(mythical_request_times_count{method=~\".+\", beast=~\"${beast}\"}[1m])))"
    }
   ]
  },
  {
   "title": "All Endpoint Latencies in ms (Last 10 mins)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 19 },
   "targets": [
    {
     "expr": "sum by (method,beast)(increase(mythical_request_times_sum{method=~\".+\", beast=~\"${beast}\"}[10m]) / increase(mythical_request_times_count{method=~\".+\", beast=~\"${beast}\"}[10m]))"
    }
   ]
  },
  {
   "title": "95th Percentile Response Latencies (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mythical_request_times_bucket[15s])) by (le, beast))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Autologged Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{job=\"alloy\"} | logfmt | status=\"Error\""
    }
   ]
  }
 ]
}